site_name: '🧪 MLOps Course'
repo_url: https://github.com/Matesanz/mlops-course
repo_name: Matesanz/mlops-course
theme:
  name: material
  theme:
  palette:
    primary: teal
  features:
    - content.code.annotate

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
  - mkdocs-jupyter


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - 'mlops_course'
  - docs
